{Cargo, SourceLib, TargetLib} = case os:type() of
  {win32, _} -> {"cargo.exe", "ezstd.dll", "ezstd.dll"};
  {unix, darwin} -> {"RUSTFLAGS='-C link-arg=-undefined -C link-arg=dynamic_lookup' cargo", "libezstd.dylib", "ezstd.so"};
  _ -> {"cargo", "libezstd.so", "ezstd.so"}
end,

os:cmd(Cargo ++ " build --release --manifest-path native/ezstd_nif/Cargo.toml"),

filelib:ensure_dir("priv/"),
file:copy("native/ezstd_nif/target/release/" ++ SourceLib, "priv/" ++ TargetLib),

CONFIG.
